### ISSUE TITLE
Document how to use 'logging'

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/observatory#5]
If I'm using the logging package, it should "just work" right?

**Comment by johnmccutchan** [comment]
What's the context?

**Comment by kevmoo** [comment]
I guess I figured it out. Use the `dart:developer` `log` function.

It'd be nice if this was documented, though. I thought there was a time when logs from `pkg/logging` were picked up here, too.

**Comment by johnmccutchan** [comment]
`dart:developer` `log` is documented and can be used independently from `pkg/logging`.

It's simple to combine `pkg/logging` and `dart:developer` `log` by writing a function that looks like this:


Logger.root.onRecord.listen((LogRecord logRecord) {
  log(logRecord.message, ....);
});
